### ISSUE TITLE
More different implementations

### ISSUE THREAD

**Issue by narimiran** [henryiii/framework_compare#1]
Hi, thanks for expanding the tests to some more different implementations.

I have run the same test in [Nim programming language](https://nim-lang.org/) and have written [a short post about it](https://narimiran.github.io/2018/05/10/python-numpy-nim.html).

From the [comments on Reddit](https://www.reddit.com/r/programming/comments/8ilinf/python_vs_numpy_vs_nim/), it seems people are interested to also see:
- [x] Cython
- [x] PyPy

Could you maybe add those versions too?

**Comment by henryiii** [comment]
Are you okay with me adding the nim example to the repo? I might add those. I really wasn't trying too hard for speed with the numba version; using a pure python like implementation might be faster on it.

**Comment by narimiran** [comment]
> Are you okay with me adding the nim example to the repo?

Yes, feel free to add the Nim example. I would appreciate if you would put [the link to the original](https://github.com/narimiran/narimiran.github.io/blob/master/code/python-numpy-nim/gradDesc.nim) as a comment in the code.

> I really wasn't trying too hard for speed with the numba version; using a pure python like implementation might be faster on it.

Some discussion about numba [here](https://www.reddit.com/r/Python/comments/8imw2z/python_vs_numpy_vs_nim/dyu5ea9/).

**Comment by henryiii** [comment]
Is there something special about compiling it? I get 3.75 seconds on it, compared to 0.5 seconds on numpy, or even less with numba...

**Comment by narimiran** [comment]
If you have run just `nim c filename.nim` that's a debug build.

To make a release build:
```
nim c -d:release filename.nim
```

**Comment by henryiii** [comment]
That's it, much better :)

**Comment by henryiii** [comment]
Added.

**Comment by henryiii** [comment]
Added Cython, PyPy, and C++11 examples. Also fixed the types in the numpy (nice speed boost) and numba examples, and added a pure Numba example. Numba's now only a hair slower than nim when running the same algorithm, and C++11 is a bit faster.
